[package]
name = "juliaup"
version = "1.4.2-alpha.0"
edition = "2018"
default-run = "juliaup"
publish = false

[profile.release]
lto = true
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
dirs = "4"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
semver = "1"
anyhow = "1"
tempfile = "3"
flate2 = "1"
tar = "0.4"
ureq = "2"
normpath = "0.3"
fs_extra = "1.2"
thiserror = "1"
indicatif = "0.16"
atty = "0.2.14"
console = "0.15"
ctrlc = "3.2.1"
url = "2"
cli-table = "0.4"
itertools = "0.10"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.28", features = ["alloc", "std", "Win32_Foundation", "Win32_System_Console"] }

[build-dependencies]
anyhow = "1"
winres = "0.1"
itertools = "0.10"
serde = {version = "1", features = ["derive"] }
serde_json = "1"
semver = "1"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "2.1"

[features]
selfupdate = []
dummy = []
